name: 'Basic Syntax Check'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  check_syntax:
    name: Check Basic Syntax
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Check Python Syntax
      run: |
        echo "Checking Python files..."
        find . -name "*.py" -type f -exec python -m py_compile {} \;
        echo "Python syntax check passed!"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Check JavaScript Syntax
      run: |
        echo "Checking JavaScript files..."
        for file in $(find . -name "*.js"); do
          echo "Checking $file"
          node --check "$file" || true
        done
        echo "JavaScript syntax check completed!"